/* ============================================================
   WhatsUp — demo data
   All people, photos, and conversations are fictional.
   Map coords are % positions on the stylized Harvard Square map.
   ============================================================ */

// Gradient pairs used to generate avatar + photo placeholders
const PALETTES = {
  sky: ["#36c6f4", "#0090c9"],
  coral: ["#ff9a76", "#e85d5d"],
  violet: ["#a78bfa", "#6d4fc4"],
  mint: ["#5ee0a0", "#2fa970"],
  gold: ["#ffd76e", "#e8a33d"],
  rose: ["#f9a8c5", "#e0608f"],
  slate: ["#94a8bb", "#5a7184"],
  teal: ["#4fd1c5", "#2b9c91"],
  plum: ["#c084fc", "#9333ea"],
};

const ME = {
  id: "me",
  name: "Alex Rivera",
  initials: "AR",
  palette: "sky",
  headline: "Harvard '27 · Economics · Building WhatsUp",
  school: "Harvard College, Class of 2027",
  work: "Founder @ WhatsUp",
  hometown: "Austin, TX",
  relationship: "Single",
  openTo: ["Networking", "Friends", "Dating"],
  x: 50, y: 52, // map position (%)
  stats: { connections: 184, irlMeets: 61, beacons: 12 },
  photos: [
    { palette: "sky", caption: "Charles River sunrise row 🚣", emoji: "🚣" },
    { palette: "gold", caption: "Tailgate w/ the blocking group", emoji: "🏈" },
    { palette: "mint", caption: "Hiking the Whites", emoji: "⛰️" },
  ],
  prompts: [
    { q: "My simple pleasure", a: "Cold brew + a window seat in Widener." },
    { q: "Ask me about", a: "Why social apps should get you OFF your phone." },
    { q: "Best way to say whats up", a: "Just walk up. I promise I'm friendly." },
  ],
  socials: ["Instagram", "LinkedIn", "X"],
};

const PEOPLE = [
  {
    id: "maya",
    name: "Maya Chen",
    initials: "MC",
    palette: "rose",
    friend: false,
    online: true,
    distance: "40 yds",
    headline: "Harvard '27 · Gov & Econ · Coffee enthusiast",
    school: "Harvard College, Class of 2027",
    work: "Research Assistant, Harvard Kennedy School",
    hometown: "Seattle, WA",
    relationship: "Single",
    openTo: ["Friends", "Dating", "Study buddies"],
    sharedContext: "In your Ec 1010b lecture · Sever Hall right now",
    x: 47, y: 47,
    photos: [
      { palette: "rose", caption: "Golden hour in the Yard", emoji: "🌅" },
      { palette: "violet", caption: "Pottery class attempt #3", emoji: "🏺" },
      { palette: "teal", caption: "Pike Place, home for the holidays", emoji: "🐟" },
    ],
    prompts: [
      { q: "You'll find me", a: "Third row of Ec 1010b, iced latte in hand." },
      { q: "Green flag I look for", a: "Says hi to people in person, not just online." },
      { q: "Together we could", a: "Find the best pastry in Harvard Square. It's research." },
    ],
    socials: ["Instagram", "LinkedIn"],
    posts: [],
  },
  {
    id: "james",
    name: "James Okafor",
    initials: "JO",
    palette: "violet",
    friend: true,
    irl: true,
    online: true,
    distance: "0.2 mi",
    headline: "Harvard '26 · CS · SWE intern @ Stripe this summer",
    school: "Harvard College, Class of 2026",
    work: "Incoming SWE Intern, Stripe",
    hometown: "Houston, TX",
    relationship: "In a relationship",
    openTo: ["Networking", "Friends"],
    sharedContext: "Met IRL at HackHarvard · 14 mutual connections",
    x: 58, y: 60,
    photos: [
      { palette: "violet", caption: "Demo day. We survived.", emoji: "💻" },
      { palette: "sky", caption: "MAC pickup runs", emoji: "🏀" },
    ],
    prompts: [
      { q: "Ask me about", a: "Shipping a hackathon project at 4am." },
      { q: "My go-to spot", a: "The MAC courts, Tuesdays at 6." },
    ],
    socials: ["LinkedIn", "GitHub", "X"],
    posts: [
      {
        type: "work",
        time: "2h",
        text: "Excited to share I'll be joining Stripe this summer as a SWE intern on the payments team! Huge thanks to everyone who did mock interviews with me — especially the ones I met through a WhatsUp beacon. 🙏",
        likes: 47,
      },
      {
        type: "photo",
        time: "1d",
        text: "Pickup at the MAC tonight, 6pm. Drop by — first intro is on me.",
        photo: { palette: "sky", caption: "MAC courts, Tuesday nights 🏀" },
        likes: 23,
      },
    ],
  },
  {
    id: "sofia",
    name: "Sofia Martinez",
    initials: "SM",
    palette: "coral",
    friend: true,
    irl: true,
    online: false,
    distance: "0.4 mi",
    headline: "HBS MBA '27 · ex-Goldman · Climate tech",
    school: "Harvard Business School, MBA 2027",
    work: "Ex-Analyst, Goldman Sachs · Exploring climate tech",
    hometown: "Miami, FL",
    relationship: "Prefer not to say",
    openTo: ["Networking", "Co-founder search"],
    sharedContext: "Met IRL at the HBS Climate Summit · 6 mutuals",
    x: 70, y: 78,
    photos: [
      { palette: "coral", caption: "Panel day @ Climate Summit", emoji: "🌎" },
      { palette: "mint", caption: "Weekend in Vermont", emoji: "🍁" },
    ],
    prompts: [
      { q: "I'm looking for", a: "A technical co-founder who cares about grid storage." },
      { q: "Best networking advice", a: "Skip the cold email. Find them on the map, say whats up." },
    ],
    socials: ["LinkedIn", "X"],
    posts: [
      {
        type: "work",
        time: "5h",
        text: "Recap from the Climate Tech Summit at Spangler: 200+ people, 30 of them found each other on WhatsUp's event scan. If you're working on storage or carbon markets, my DMs (and my map pin) are open this week.",
        likes: 89,
      },
    ],
  },
  {
    id: "liam",
    name: "Liam Goldberg",
    initials: "LG",
    palette: "slate",
    friend: false,
    online: true,
    distance: "0.5 mi",
    headline: "HBS MBA '26 · ex-McKinsey · Angel scout",
    school: "Harvard Business School, MBA 2026",
    work: "Ex-Associate, McKinsey & Co · Scout, Sequoia",
    hometown: "New York, NY",
    relationship: "Prefer not to say",
    openTo: ["Networking", "Investing"],
    sharedContext: "At HBS Networking Night · 3 mutual connections",
    x: 74, y: 82,
    photos: [
      { palette: "slate", caption: "Speaking at FinTech Club", emoji: "🎤" },
    ],
    prompts: [
      { q: "Talk to me about", a: "Consumer social, marketplaces, and why most pitches bore me." },
      { q: "Best way to pitch me", a: "In person, 60 seconds, no deck." },
    ],
    socials: ["LinkedIn"],
    posts: [],
  },
  {
    id: "priya",
    name: "Priya Patel",
    initials: "PP",
    palette: "teal",
    friend: true,
    irl: false,
    online: true,
    distance: "90 yds",
    headline: "Harvard '27 · Neuro pre-med · Tea > coffee",
    school: "Harvard College, Class of 2027",
    work: "Research Assistant, MGH Neurology",
    hometown: "Jersey City, NJ",
    relationship: "Single",
    openTo: ["Friends", "Study buddies"],
    sharedContext: "Connected last week · You haven't met IRL yet",
    x: 44, y: 58,
    photos: [
      { palette: "teal", caption: "Lab day (the pipette won)", emoji: "🧪" },
      { palette: "gold", caption: "Diwali at the SAC", emoji: "🪔" },
    ],
    prompts: [
      { q: "My simple pleasure", a: "Chai from Tatte + people-watching in the Square." },
      { q: "We should meet if", a: "You also pretend to study at Lamont but mostly chat." },
    ],
    posts: [
      {
        type: "prompt",
        time: "3h",
        promptQ: "My simple pleasure",
        text: "Chai from Tatte + people-watching in the Square.",
        likes: 31,
      },
    ],
    socials: ["Instagram"],
  },
  {
    id: "noah",
    name: "Noah Kim",
    initials: "NK",
    palette: "gold",
    friend: false,
    online: false,
    distance: "0.3 mi",
    headline: "Product Designer @ Figma · GSD '25",
    school: "Harvard GSD, MDes 2025",
    work: "Product Designer, Figma",
    hometown: "Los Angeles, CA",
    relationship: "Single",
    openTo: ["Networking", "Friends", "Dating"],
    sharedContext: "Often at Blue Bottle around now",
    x: 38, y: 66,
    photos: [
      { palette: "gold", caption: "Sketchbook > screens, sometimes", emoji: "✏️" },
      { palette: "plum", caption: "Gallery night in SoWa", emoji: "🖼️" },
    ],
    prompts: [
      { q: "A perfect first meet", a: "Coffee walk along the Charles. 30 minutes, no agenda." },
      { q: "Unpopular opinion", a: "Most apps are designed to trap you. The good ones let you go." },
    ],
    socials: ["Instagram", "LinkedIn"],
    posts: [],
  },
  {
    id: "emma",
    name: "Emma Rossi",
    initials: "ER",
    palette: "plum",
    friend: true,
    irl: true,
    online: true,
    distance: "120 yds",
    headline: "Harvard '26 · History of Art · Museum kid",
    school: "Harvard College, Class of 2026",
    work: "Curatorial Intern, Harvard Art Museums",
    hometown: "Providence, RI",
    relationship: "Single",
    openTo: ["Friends", "Dating"],
    sharedContext: "Met IRL via her beacon at Blue Bottle · 9 mutuals",
    x: 40, y: 44,
    photos: [
      { palette: "plum", caption: "Behind the scenes at the Fogg", emoji: "🖼️" },
      { palette: "rose", caption: "Sunday market haul", emoji: "🌷" },
    ],
    prompts: [
      { q: "You'll find me", a: "Wherever the good light is." },
      { q: "Together we could", a: "Do a museum speed-run: 45 min, 3 favorites, then gelato." },
    ],
    posts: [
      {
        type: "photo",
        time: "6h",
        text: "New exhibition opens Friday — I helped hang it! Come through, I'll be dropping a beacon at the museum 5–7pm.",
        photo: { palette: "plum", caption: "Opening night prep @ the Fogg 🖼️" },
        likes: 56,
      },
    ],
    socials: ["Instagram", "LinkedIn"],
  },
  {
    id: "david",
    name: "David Park",
    initials: "DP",
    palette: "mint",
    friend: false,
    online: true,
    distance: "0.5 mi",
    headline: "University Recruiter @ Anthropic · Here for the career fair",
    school: "UC Berkeley '18",
    work: "University Recruiter, Anthropic",
    hometown: "San Francisco, CA",
    relationship: "Prefer not to say",
    openTo: ["Networking", "Hiring"],
    sharedContext: "At HBS Networking Night · Hiring for 2027 internships",
    x: 76, y: 79,
    photos: [
      { palette: "mint", caption: "Career fair circuit, stop 4 of 9", emoji: "🧳" },
    ],
    prompts: [
      { q: "Come say whats up if", a: "You want the real story on what we look for. No application portal can tell you that." },
    ],
    socials: ["LinkedIn"],
    posts: [],
  },
];

// Stylized landmarks for the map (positions in % of map canvas)
const PLACES = [
  { id: "yard", label: "Harvard Yard", x: 50, y: 41, type: "green" },
  { id: "sever", label: "Sever Hall", x: 47, y: 45.5, type: "label" },
  { id: "widener", label: "Widener Library", x: 52, y: 47, type: "label" },
  { id: "square", label: "Harvard Square", x: 43, y: 62, type: "label" },
  { id: "charles", label: "Charles River", x: 58, y: 93, type: "water" },
  { id: "hbs", label: "Harvard Business School", x: 73, y: 84, type: "label" },
  { id: "lamont", label: "Lamont Library", x: 57, y: 50, type: "label" },
  { id: "mac", label: "Malkin Athletic Center", x: 56, y: 67, type: "label" },
];

const HOTSPOTS = [
  {
    id: "spangler",
    name: "HBS Networking Night",
    place: "Spangler Center",
    icon: "🤝",
    count: 38,
    x: 73, y: 80,
    sub: "Career mixer · 6–9pm · 38 people scanned in",
    people: ["sofia", "liam", "david"],
  },
  {
    id: "bluebottle",
    name: "Blue Bottle Coffee",
    place: "Harvard Square",
    icon: "☕",
    count: 11,
    x: 39, y: 64,
    sub: "Busy right now · 11 people here",
    people: ["noah"],
  },
  {
    id: "lamont-hs",
    name: "Lamont Library",
    place: "Late-night study floor",
    icon: "📚",
    count: 19,
    x: 57, y: 52,
    sub: "Quiet grind · 19 people here",
    people: [],
  },
  {
    id: "mac-hs",
    name: "Pickup Basketball",
    place: "MAC Courts",
    icon: "🏀",
    count: 8,
    x: 56, y: 69,
    sub: "Game running · 8 people here",
    people: ["james"],
  },
];

const BEACONS = [
  {
    id: "b1",
    personId: "emma",
    text: "Sketching at Blue Bottle til 4 — come say whats up, I'll buy round two ☕",
    place: "Blue Bottle, Harvard Sq",
    expires: "1h 12m left",
    joined: 3,
  },
  {
    id: "b2",
    personId: "james",
    text: "Pickup basketball at the MAC, 6pm. Need 2 more. All levels 🏀",
    place: "MAC Courts",
    expires: "Starts in 40m",
    joined: 6,
  },
  {
    id: "b3",
    personId: "sofia",
    text: "Post-summit debrief at Spangler café. Talking climate tech + co-founder hunting 🌎",
    place: "Spangler Center, HBS",
    expires: "2h 30m left",
    joined: 9,
  },
];

const CHATS = [
  {
    personId: "emma",
    unread: true,
    time: "2:14 PM",
    messages: [
      { from: "them", text: "ok the beacon experiment worked WAY too well" },
      { from: "them", text: "three people I'd never met came up and said whats up at Blue Bottle 😂" },
      { from: "me", text: "haha that's literally the whole point!! who were they" },
      { from: "them", text: "a GSD designer, someone from my Gen Ed, and a guy who just wanted my table" },
      { from: "them", text: "2 out of 3 is a win. You coming to the exhibition Friday?" },
      { type: "meet", title: "Emma suggested meeting IRL", sub: "Fogg Museum · Friday 5:00 PM" },
    ],
  },
  {
    personId: "james",
    unread: true,
    time: "1:48 PM",
    messages: [
      { from: "me", text: "yo congrats on Stripe!! saw the post" },
      { from: "them", text: "appreciate you 🙏 the beacon mock interviews honestly carried me" },
      { from: "them", text: "you pulling up to the MAC tonight? need bodies" },
    ],
  },
  {
    personId: "sofia",
    unread: false,
    time: "11:02 AM",
    messages: [
      { from: "them", text: "Hey! Saw we were both at the climate summit — your founder talk question was sharp" },
      { from: "me", text: "thanks for saying that! I was nervous to ask haha" },
      { from: "them", text: "Never be. That's the whole game. Coffee this week? I'm usually pinned at Spangler" },
      { from: "me", text: "yes — I'll check the map and come find you 🤝" },
    ],
  },
  {
    personId: "priya",
    unread: false,
    time: "Yesterday",
    messages: [
      { from: "them", text: "we've been connected a week and still haven't met irl, this is against the spirit of the app 😤" },
      { from: "me", text: "you're right. tatte chai, tomorrow after lecture?" },
      { from: "them", text: "deal. I'll find you on the map 🫖" },
    ],
  },
];

// Feed = friends' posts + system nudges, pre-sorted
const FEED_EXTRA = [
  {
    type: "nudge",
    title: "Maya is 40 yds away 👀",
    text: "She's in your Ec 1010b lecture and open to meeting people. The map says you two cross paths a lot.",
    cta: "See who's nearby",
  },
];
